import 'package:flutter/material.dart';
import 'package:loven/core/res/theme/app_theme.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

// Generated by: dart run build_runner build -d
import 'main.directories.g.dart';

void main() {
  runApp(const LovenWidgetbookApp());
}

@widgetbook.App()
class LovenWidgetbookApp extends StatelessWidget {
  const LovenWidgetbookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      directories: directories,
      addons: [
        MaterialThemeAddon(
          themes: [
            WidgetbookTheme(
              name: 'Light',
              data: AppTheme.lightTheme,
            ),
            WidgetbookTheme(
              name: 'Dark',
              data: AppTheme.darkTheme,
            ),
          ],
        ),
        ViewportAddon([
          IosViewports.iPhone13,
          IosViewports.iPhone13ProMax,
        ]),
      ],
    );
  }
}
